/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.keylane;

import java.io.IOException;

public class Main {
    public static void main(String[] args) throws IOException {
        SLAReportGenerator generator = new SLAReportGenerator();
        generator.generate(args[0],args[1]);
    }
}
